import { ensureUniqueKey } from './registry';
import type { FormField } from './types';

export const JSON_SCHEMA_DIALECT = 'https://json-schema.org/draft/2020-12/schema';

// Add non-standard metadata for UI rendering
const addUIMetadata = (config: Record<string, unknown>): Record<string, unknown> => {
  const filteredEntries = Object.entries(config).filter(([, value]) => !!value);
  return filteredEntries.length ? { ui: Object.fromEntries(filteredEntries) } : {};
};

const fieldToPropertySchema = (field: FormField): Record<string, unknown> => {
  switch (field.type) {
    case 'text':
      return {
        title: field.title,
        type: 'string',
        ...(field.minLength !== undefined && { minLength: field.minLength }),
        ...(field.maxLength !== undefined && { maxLength: field.maxLength }),
        ...addUIMetadata({ placeholder: field.placeholder }),
      };
    case 'number':
      return {
        title: field.title,
        type: field.isFloat ? 'number' : 'integer',
        ...(field.min !== undefined && { minimum: field.min }),
        ...(field.max !== undefined && { maximum: field.max }),
      };
    case 'selection': {
      const enumValues = field.options.map((option) => option.value);
      return field.multiple
        ? { title: field.title, type: 'array', items: { enum: enumValues }, uniqueItems: true }
        : { title: field.title, enum: enumValues };
    }
  }
};

// `generatedAt` defaults to the real current time but can be overridden for testing
export const generateJsonSchema = (
  fields: FormField[],
  generatedAt: Date = new Date(),
): Record<string, unknown> => {
  const usedKeys = new Set<string>();
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  fields.forEach((field) => {
    const key = ensureUniqueKey(field.key, usedKeys);
    usedKeys.add(key);
    properties[key] = fieldToPropertySchema(field);
    if (field.required) required.push(key);
  });

  return {
    $schema: JSON_SCHEMA_DIALECT,
    $comment: `Generated by json-schema-form-builder on ${generatedAt.toISOString()}`,
    type: 'object',
    properties,
    ...(required.length > 0 && { required }),
  };
};
