import { isSelectionField } from './guards';
import { ensureUniqueKey } from './registry';
import type { ConditionGroup, FormField } from './types';

export const JSON_SCHEMA_DIALECT = 'https://json-schema.org/draft/2020-12/schema';

// Add non-standard metadata for UI rendering
const addUIMetadata = (config: Record<string, unknown>): Record<string, unknown> => {
  const filteredEntries = Object.entries(config).filter(([, value]) => !!value);
  return filteredEntries.length ? { ui: Object.fromEntries(filteredEntries) } : {};
};

const fieldToPropertySchema = (field: FormField): Record<string, unknown> => {
  switch (field.type) {
    case 'text':
      return {
        title: field.title,
        type: 'string',
        ...(field.minLength !== undefined && { minLength: field.minLength }),
        ...(field.maxLength !== undefined && { maxLength: field.maxLength }),
        ...addUIMetadata({ placeholder: field.placeholder }),
      };
    case 'number':
      return {
        title: field.title,
        type: field.isFloat ? 'number' : 'integer',
        ...(field.min !== undefined && { minimum: field.min }),
        ...(field.max !== undefined && { maximum: field.max }),
      };
    case 'selection': {
      const enumValues = field.options.map((option) => option.value);
      return field.multiple
        ? { title: field.title, type: 'array', items: { enum: enumValues }, uniqueItems: true }
        : { title: field.title, enum: enumValues };
    }
  }
};

interface KeyedField {
  field: FormField;
  key: string;
}

// A condition's referenced value must be `required` alongside its `enum`/`contains` check -
// without it, an instance that omits the referenced property entirely would trivially
// satisfy `properties`, wrongly matching `if` even though nothing was ever selected.
const buildIfSchema = (
  group: ConditionGroup,
  keyedFields: KeyedField[],
): Record<string, unknown> | null => {
  switch (group.operator) {
    case 'and': {
      const properties: Record<string, unknown> = {};
      const required: string[] = [];

      group.rules.forEach((rule) => {
        const referenced = keyedFields.find(({ field }) => field.key === rule.field);
        if (!referenced) return;

        properties[referenced.key] =
          isSelectionField(referenced.field) && referenced.field.multiple
            ? { contains: { enum: rule.values } }
            : { enum: rule.values };
        required.push(referenced.key);
      });

      return Object.keys(properties).length > 0 ? { properties, required } : null;
    }
  }
};

// `generatedAt` defaults to the real current time but can be overridden for testing
export const generateJsonSchema = (
  fields: FormField[],
  generatedAt: Date = new Date(),
): Record<string, unknown> => {
  const usedKeys = new Set<string>();
  const keyedFields: KeyedField[] = fields.map((field) => {
    const key = ensureUniqueKey(field.key, usedKeys);
    usedKeys.add(key);
    return { field, key };
  });

  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  const allOf: Record<string, unknown>[] = [];

  keyedFields.forEach(({ field, key }) => {
    const group = field.conditions;
    const ifSchema = group && group.rules.length > 0 ? buildIfSchema(group, keyedFields) : null;

    if (!ifSchema) {
      properties[key] = fieldToPropertySchema(field);
      if (field.required) required.push(key);
      return;
    }

    allOf.push({
      if: ifSchema,
      then: {
        properties: { [key]: fieldToPropertySchema(field) },
        ...(field.required && { required: [key] }),
      },
    });
  });

  return {
    $schema: JSON_SCHEMA_DIALECT,
    $comment: `Generated by json-schema-form-builder on ${generatedAt.toISOString()}`,
    type: 'object',
    properties,
    ...(required.length > 0 && { required }),
    ...(allOf.length > 0 && { allOf }),
  };
};
