import { describe, it, expect } from 'vitest';

import { createField } from '../registry';
import {
  JSON_SCHEMA_DIALECT,
  SchemaImportError,
  generateJsonSchema,
  parseJsonSchema,
} from '../schema';
import type { NumberField, SelectionField, TextField } from '../types';

const GENERATED_AT = new Date('2026-08-01T12:00:00.000Z');

describe('generateJsonSchema', () => {
  it('produces an empty draft 2020-12 object schema with no fields', () => {
    const schema = generateJsonSchema([], GENERATED_AT);

    expect(schema).toEqual({
      $schema: JSON_SCHEMA_DIALECT,
      $comment: `Generated by json-schema-form-builder on ${GENERATED_AT.toISOString()}`,
      type: 'object',
      properties: {},
    });
  });

  it('maps a text field to a string property, only including bounds that are set', () => {
    const field: TextField = { ...(createField('text') as TextField), minLength: 2 };

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: { title: field.title, type: 'string', minLength: 2 },
    });
  });

  it('maps a text field placeholder to a ui.placeholder hint', () => {
    const field: TextField = { ...(createField('text') as TextField), placeholder: 'Jane Doe' };

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: { title: field.title, type: 'string', ui: { placeholder: 'Jane Doe' } },
    });
  });

  it('maps a number field to integer or number based on isFloat, with min/max as bounds', () => {
    const wholeNumber: NumberField = {
      ...(createField('number') as NumberField),
      isFloat: false,
      min: 0,
      max: 10,
    };
    const decimal: NumberField = {
      ...(createField('number') as NumberField),
      key: 'decimalField',
      isFloat: true,
    };

    const schema = generateJsonSchema([wholeNumber, decimal], GENERATED_AT);

    expect(schema.properties).toEqual({
      [wholeNumber.key]: {
        title: wholeNumber.title,
        type: 'integer',
        minimum: 0,
        maximum: 10,
      },
      decimalField: { title: decimal.title, type: 'number' },
    });
  });

  it('maps a single-choice selection field to an enum of option values', () => {
    const field = createField('selection') as SelectionField;

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: { title: field.title, enum: ['option_1'] },
    });
  });

  it('maps a multi-choice selection field to a unique-items array of an enum', () => {
    const field: SelectionField = {
      ...(createField('selection') as SelectionField),
      multiple: true,
    };

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: {
        title: field.title,
        type: 'array',
        items: { enum: ['option_1'] },
        uniqueItems: true,
      },
    });
  });

  it('lists only required fields in the required array, and omits it entirely when none are required', () => {
    const optional = createField('text');
    const required: TextField = {
      ...(createField('text') as TextField),
      key: 'requiredField',
      required: true,
    };

    expect(generateJsonSchema([optional])).not.toHaveProperty('required');
    expect(generateJsonSchema([optional, required]).required).toEqual(['requiredField']);
  });

  it('deduplicates colliding keys rather than letting one property overwrite another', () => {
    const first: TextField = { ...(createField('text') as TextField), key: 'name' };
    const second: TextField = { ...(createField('text') as TextField), key: 'name' };

    const schema = generateJsonSchema([first, second], GENERATED_AT);

    expect(Object.keys(schema.properties as object)).toEqual(['name', 'name2']);
  });

  describe('conditional fields', () => {
    it('moves a conditional field into allOf[].then instead of top-level properties', () => {
      const trigger: SelectionField = {
        ...(createField('selection') as SelectionField),
        key: 'country',
      };
      const dependent: TextField = {
        ...(createField('text') as TextField),
        key: 'state',
        conditions: {
          operator: 'and',
          rules: [{ id: 'rule-1', field: 'country', type: 'equals', values: ['option_1'] }],
        },
      };

      const schema = generateJsonSchema([trigger, dependent], GENERATED_AT);

      expect(schema.properties).toEqual({
        country: { title: trigger.title, enum: ['option_1'] },
      });
      expect(schema.allOf).toEqual([
        {
          if: { properties: { country: { enum: ['option_1'] } }, required: ['country'] },
          then: { properties: { state: { title: dependent.title, type: 'string' } } },
        },
      ]);
    });

    it('adds the dependent key to the then branch required array when the field itself is required', () => {
      const trigger: SelectionField = {
        ...(createField('selection') as SelectionField),
        key: 'country',
      };
      const dependent: TextField = {
        ...(createField('text') as TextField),
        key: 'state',
        required: true,
        conditions: {
          operator: 'and',
          rules: [{ id: 'rule-1', field: 'country', type: 'equals', values: ['option_1'] }],
        },
      };

      const schema = generateJsonSchema([trigger, dependent], GENERATED_AT);

      expect(schema.allOf).toEqual([
        {
          if: { properties: { country: { enum: ['option_1'] } }, required: ['country'] },
          then: {
            properties: { state: { title: dependent.title, type: 'string' } },
            required: ['state'],
          },
        },
      ]);
      expect(schema).not.toHaveProperty('required');
    });

    it('uses "contains" instead of "enum" when the referenced field is a multi-select', () => {
      const trigger: SelectionField = {
        ...(createField('selection') as SelectionField),
        key: 'tags',
        multiple: true,
      };
      const dependent: TextField = {
        ...(createField('text') as TextField),
        key: 'note',
        conditions: {
          operator: 'and',
          rules: [{ id: 'rule-1', field: 'tags', type: 'equals', values: ['urgent'] }],
        },
      };

      const schema = generateJsonSchema([trigger, dependent], GENERATED_AT);

      expect(schema.allOf).toEqual([
        {
          if: {
            properties: { tags: { contains: { enum: ['urgent'] } } },
            required: ['tags'],
          },
          then: { properties: { note: { title: dependent.title, type: 'string' } } },
        },
      ]);
    });

    it('coerces rule values to numbers when the referenced field is a number field', () => {
      const trigger: NumberField = { ...(createField('number') as NumberField), key: 'age' };
      const dependent: TextField = {
        ...(createField('text') as TextField),
        key: 'guardianName',
        conditions: {
          operator: 'and',
          rules: [{ id: 'rule-1', field: 'age', type: 'equals', values: ['17', '18'] }],
        },
      };

      const schema = generateJsonSchema([trigger, dependent], GENERATED_AT);

      expect(schema.allOf).toEqual([
        {
          if: { properties: { age: { enum: [17, 18] } }, required: ['age'] },
          then: { properties: { guardianName: { title: dependent.title, type: 'string' } } },
        },
      ]);
    });

    it('merges multiple rules into one if.properties/required object', () => {
      const country: SelectionField = {
        ...(createField('selection') as SelectionField),
        key: 'country',
      };
      const plan: SelectionField = { ...(createField('selection') as SelectionField), key: 'plan' };
      const dependent: TextField = {
        ...(createField('text') as TextField),
        key: 'vatNumber',
        conditions: {
          operator: 'and',
          rules: [
            { id: 'rule-1', field: 'country', type: 'equals', values: ['option_1'] },
            { id: 'rule-2', field: 'plan', type: 'equals', values: ['option_1'] },
          ],
        },
      };

      const schema = generateJsonSchema([country, plan, dependent], GENERATED_AT);

      expect(schema.allOf).toEqual([
        {
          if: {
            properties: { country: { enum: ['option_1'] }, plan: { enum: ['option_1'] } },
            required: ['country', 'plan'],
          },
          then: { properties: { vatNumber: { title: dependent.title, type: 'string' } } },
        },
      ]);
    });

    it('treats a field with no rules, or with an unresolvable reference, as unconditional', () => {
      const emptyGroup: TextField = {
        ...(createField('text') as TextField),
        key: 'a',
        conditions: { operator: 'and', rules: [] },
      };
      const danglingRule: TextField = {
        ...(createField('text') as TextField),
        key: 'b',
        conditions: {
          operator: 'and',
          rules: [{ id: 'rule-1', field: 'missing', type: 'equals', values: ['x'] }],
        },
      };

      const schema = generateJsonSchema([emptyGroup, danglingRule], GENERATED_AT);

      expect(schema.properties).toEqual({
        a: { title: emptyGroup.title, type: 'string' },
        b: { title: danglingRule.title, type: 'string' },
      });
      expect(schema).not.toHaveProperty('allOf');
    });
  });
});

describe('parseJsonSchema', () => {
  it('throws a SchemaImportError when there is no properties object to import', () => {
    expect(() => parseJsonSchema({ type: 'object' })).toThrow(SchemaImportError);
    expect(() => parseJsonSchema('not a schema')).toThrow(SchemaImportError);
    expect(() => parseJsonSchema(null)).toThrow(SchemaImportError);
  });

  it('round-trips a schema generated by generateJsonSchema back into equivalent fields', () => {
    const text: TextField = {
      ...(createField('text') as TextField),
      required: true,
      minLength: 2,
      maxLength: 10,
      placeholder: 'Jane Doe',
    };
    const number: NumberField = {
      ...(createField('number') as NumberField),
      key: 'age',
      isFloat: true,
      min: 0,
      max: 120,
    };
    const selection: SelectionField = {
      ...(createField('selection') as SelectionField),
      key: 'country',
      options: [
        { id: 'x', label: 'United Kingdom', value: 'uk' },
        { id: 'y', label: 'United States', value: 'us' },
      ],
    };
    const multiSelect: SelectionField = {
      ...(createField('selection') as SelectionField),
      key: 'tags',
      multiple: true,
    };
    const dependent: TextField = {
      ...(createField('text') as TextField),
      key: 'state',
      required: true,
      conditions: {
        operator: 'and',
        rules: [{ id: 'rule-1', field: 'country', type: 'equals', values: ['uk'] }],
      },
    };

    const schema = generateJsonSchema(
      [text, number, selection, multiSelect, dependent],
      GENERATED_AT,
    );
    const result = parseJsonSchema(schema);

    expect(result.ignored).toEqual([]);
    expect(result.fields).toHaveLength(5);

    const byKey = Object.fromEntries(result.fields.map((field) => [field.key, field]));
    expect(byKey[text.key]).toMatchObject({
      type: 'text',
      required: true,
      minLength: 2,
      maxLength: 10,
      placeholder: 'Jane Doe',
    });
    expect(byKey.age).toMatchObject({ type: 'number', isFloat: true, min: 0, max: 120 });
    // Labels aren't part of the exported shape, so they fall back to the value on re-import.
    expect((byKey.country as SelectionField).options.map((option) => option.value)).toEqual([
      'uk',
      'us',
    ]);
    expect((byKey.country as SelectionField).options.map((option) => option.label)).toEqual([
      'uk',
      'us',
    ]);
    expect(byKey.tags).toMatchObject({ type: 'selection', multiple: true });
    expect(byKey.state).toMatchObject({
      type: 'text',
      required: true,
      conditions: {
        operator: 'and',
        rules: [{ field: 'country', type: 'equals', values: ['uk'] }],
      },
    });
  });

  it('marks fields required from the required array, ignoring unknown keys silently', () => {
    const schema = {
      type: 'object',
      properties: { name: { type: 'string' } },
      required: ['name', 'ghost'],
    };

    const result = parseJsonSchema(schema);

    expect(result.fields).toMatchObject([{ key: 'name', required: true }]);
    expect(result.ignored).toEqual([]);
  });

  it('skips properties whose type it cannot model, and reports each one', () => {
    const schema = {
      type: 'object',
      properties: {
        isActive: { type: 'boolean' },
        profile: { type: 'object', properties: {} },
      },
    };

    const result = parseJsonSchema(schema);

    expect(result.fields).toEqual([]);
    expect(result.ignored).toEqual([
      'Property "isActive": unsupported type "boolean", skipped',
      'Property "profile": unsupported type "object", skipped',
    ]);
  });

  it('imports what it recognizes on a property and reports unsupported keywords on it', () => {
    const schema = {
      type: 'object',
      properties: {
        email: { title: 'Email', type: 'string', format: 'email', pattern: '^.+@.+$' },
      },
    };

    const result = parseJsonSchema(schema);

    expect(result.fields).toMatchObject([{ type: 'text', title: 'Email', key: 'email' }]);
    expect(result.ignored).toEqual([
      'Property "email": ignored unsupported keyword(s) "format, pattern"',
    ]);
  });

  it('skips a malformed allOf entry instead of throwing', () => {
    const schema = {
      type: 'object',
      properties: { country: { enum: ['uk'] } },
      allOf: [
        {
          if: { properties: { country: { type: 'string' } } },
          then: { properties: { state: { type: 'string' } } },
        },
      ],
    };

    const result = parseJsonSchema(schema);

    expect(result.fields).toMatchObject([{ key: 'country' }]);
    expect(result.ignored).toEqual([
      'allOf[0]: condition on "country" not recognized, skipped',
      'allOf[0]: skipped, no usable conditions',
    ]);
  });

  it('skips a then-branch property that collides with an already-imported key', () => {
    const schema = {
      type: 'object',
      properties: { country: { enum: ['uk'] }, state: { type: 'string' } },
      allOf: [
        {
          if: { properties: { country: { enum: ['uk'] } } },
          then: { properties: { state: { type: 'string' } } },
        },
      ],
    };

    const result = parseJsonSchema(schema);

    expect(result.fields).toHaveLength(2);
    expect(result.ignored).toEqual(['allOf[0]: duplicate property "state", skipped']);
  });

  it('reports unrecognized root keywords without failing the import', () => {
    const schema = {
      type: 'object',
      properties: {},
      additionalProperties: false,
    };

    const result = parseJsonSchema(schema);

    expect(result.fields).toEqual([]);
    expect(result.ignored).toEqual(['Root: unsupported keyword "additionalProperties" ignored']);
  });
});
