import { describe, it, expect } from 'vitest';

import { createField } from '../registry';
import { JSON_SCHEMA_DIALECT, generateJsonSchema } from '../schema';
import type { NumberField, SelectionField, TextField } from '../types';

const GENERATED_AT = new Date('2026-08-01T12:00:00.000Z');

describe('generateJsonSchema', () => {
  it('produces an empty draft 2020-12 object schema with no fields', () => {
    const schema = generateJsonSchema([], GENERATED_AT);

    expect(schema).toEqual({
      $schema: JSON_SCHEMA_DIALECT,
      $comment: `Generated by json-schema-form-builder on ${GENERATED_AT.toISOString()}`,
      type: 'object',
      properties: {},
    });
  });

  it('maps a text field to a string property, only including bounds that are set', () => {
    const field: TextField = { ...(createField('text') as TextField), minLength: 2 };

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: { title: field.title, type: 'string', minLength: 2 },
    });
  });

  it('maps a number field to integer or number based on isFloat, with min/max as bounds', () => {
    const wholeNumber: NumberField = {
      ...(createField('number') as NumberField),
      isFloat: false,
      min: 0,
      max: 10,
    };
    const decimal: NumberField = {
      ...(createField('number') as NumberField),
      key: 'decimalField',
      isFloat: true,
    };

    const schema = generateJsonSchema([wholeNumber, decimal], GENERATED_AT);

    expect(schema.properties).toEqual({
      [wholeNumber.key]: {
        title: wholeNumber.title,
        type: 'integer',
        minimum: 0,
        maximum: 10,
      },
      decimalField: { title: decimal.title, type: 'number' },
    });
  });

  it('maps a single-choice selection field to an enum of option values', () => {
    const field = createField('selection') as SelectionField;

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: { title: field.title, enum: ['option_1'] },
    });
  });

  it('maps a multi-choice selection field to a unique-items array of an enum', () => {
    const field: SelectionField = {
      ...(createField('selection') as SelectionField),
      multiple: true,
    };

    const schema = generateJsonSchema([field], GENERATED_AT);

    expect(schema.properties).toEqual({
      [field.key]: {
        title: field.title,
        type: 'array',
        items: { enum: ['option_1'] },
        uniqueItems: true,
      },
    });
  });

  it('lists only required fields in the required array, and omits it entirely when none are required', () => {
    const optional = createField('text');
    const required: TextField = {
      ...(createField('text') as TextField),
      key: 'requiredField',
      required: true,
    };

    expect(generateJsonSchema([optional])).not.toHaveProperty('required');
    expect(generateJsonSchema([optional, required]).required).toEqual(['requiredField']);
  });

  it('deduplicates colliding keys rather than letting one property overwrite another', () => {
    const first: TextField = { ...(createField('text') as TextField), key: 'name' };
    const second: TextField = { ...(createField('text') as TextField), key: 'name' };

    const schema = generateJsonSchema([first, second], GENERATED_AT);

    expect(Object.keys(schema.properties as object)).toEqual(['name', 'name2']);
  });
});
